###
# Stages
###
stages:
  - vendor
  - test
  - build-web
  - build
  - build-image
###
# Anchors
###
# Cache
.cache_vendor: &cache_vendor
  cache:
    key: vendor
    policy: pull-push
    paths: &cache_vendor_path
      - vendor/

.cache_vendor_pull: &cache_vendor_pull
  cache:
    key: vendor
    policy: pull
    paths: *cache_vendor_path

# Only/Except
.only_master: &only_master
  only:
    - master
  except:
    - tags

.only_develop: &only_develop
  only:
    - develop
  except:
    - tags

.only_branches: &only_branches
  only:
    - branches
  except:
    - master
    - develop
    - tags

.only_master_tag: &only_master_tag
  only:
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/
  except:
    - branches

.only_develop_tag: &only_develop_tag
  only:
    - /^v[0-9]+\.[0-9]+\.[0-9]+-dev$/
  except:
    - branches

# Docker
.docker_build_push: &docker_build_push |-
  docker build --pull -f build/Dockerfile -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}" .
  docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"

###
# Jobs
###

# Vendor
vendor:
  stage: vendor
  image: golang:1.13-alpine
  script:
    - apk add --no-cache make
    - make vendor
  <<: *cache_vendor

# Test
test:test:
  stage: test
  image: golang:1.13-buster
  script:
    - make test
  <<: *cache_vendor_pull

# Lint
test:lint:
  stage: test
  image: golangci/golangci-lint:latest
  script:
    - make lint
  <<: *cache_vendor_pull

# Build web
build-web:web:
  stage: build-web
  needs:
    - "test:test"
    - "test:lint"
  image: node:12-alpine
  script:
    - apk add --no-cache make
    - make web
  cache:
    key: vendor-web
    policy: pull-push
    paths:
      - web/trackarr-ui/node_modules
  artifacts:
    name: web_${CI_COMMIT_SHORT_SHA}
    paths:
      - web/trackarr-ui/dist/

# Build binary template
.build-binary:
  stage: build
  needs:
    - "build-web:web"
  dependencies:
    - build-web:web
  image: golang:1.13-alpine
  before_script:
    # Install dependencies
    - apk add --no-cache make git curl
    - go get github.com/GeertJohan/go.rice/rice
    - curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | BINDIR=/usr/local/bin/ sh
  script:
    # Run goreleaser
    - make snapshot
  <<: *cache_vendor_pull
  artifacts:
    name: build_${CI_COMMIT_SHORT_SHA}
    paths:
      - dist/

# Master release
build:master-publish:
  extends: .build-binary
  script:
    - make publish SKIP_WEB=true
  <<: *only_master_tag

# Master build
build:master:
  extends: .build-binary
  script:
    - make snapshot SKIP_WEB=true
  <<: *only_master

# Develop release
build:develop-publish:
  extends: .build-binary
  script:
    - make publish SKIP_WEB=true
  <<: *only_develop_tag

# Develop build
build:develop:
  extends: .build-binary
  script:
    - make snapshot SKIP_WEB=true
  <<: *only_develop

build:branch:
  extends: .build-binary
  script:
    - make snapshot SKIP_WEB=true
  <<: *only_branches
  when: manual

# Build image template
.build-image:
  stage: build-image
  image: docker:stable
  services:
    - docker:stable-dind
  before_script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" ${CI_REGISTRY}

build-image:master-publish:
  extends: .build-image
  dependencies:
    - build:master-publish
  script:
    - *docker_build_push
    - |-
      # Tag version from git tag
      docker tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}" "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
      docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
      # Tag latest
      docker tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}" "${CI_REGISTRY_IMAGE}:latest"
      docker push "${CI_REGISTRY_IMAGE}:latest"
  <<: *only_master_tag

build-image:master:
  extends: .build-image
  dependencies:
    - build:master
  script:
    - *docker_build_push
    - |-
      # Tag branch
      docker tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}" "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
      docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
  <<: *only_master

build-image:develop-publish:
  extends: .build-image
  dependencies:
    - build:develop-publish
  script:
    - *docker_build_push
    - |-
      # Tag version from git tag
      docker tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}" "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
      docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
      # Tag latest-dev
      docker tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}" "${CI_REGISTRY_IMAGE}:latest-dev"
      docker push "${CI_REGISTRY_IMAGE}:latest-dev"
  <<: *only_develop_tag

build-image:develop:
  extends: .build-image
  dependencies:
    - build:develop
  script:
    - *docker_build_push
    - |-
      # Tag branch
      docker tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}" "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
      docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
  <<: *only_develop

build-image:branch:
  extends: .build-image
  dependencies:
    - build:branch
  script:
    - *docker_build_push
  <<: *only_branches
  when: manual
